
BATCH_SIZE = 1
TEST_PERCENT = 0.2
PATTERNS_FILE = "patterns.pt"
LEARNING_RATE = 1e-2
EPOCHS = 200
TRESHOLD = 0.75
RUN_NAME = "Primo"
SIZE_PATTERNS = 9 # DISPARI
POINTS = "/home/jcolombini/GENEO/points.txt"