
BATCH_SIZE = 8
TEST_PERCENT = 0.2
PATTERNS_FILE = "patterns.pt"
LEARNING_RATE = 2e-3
EPOCHS = 10
SIZE_PATTERNS = 7 # DISPARI
POINTS_PER_IMAGE = 2
NUM_IMAGES = 100
# RUN_NAME = "BENCHMARK_CNN"
RUN_NAME = "LR_"+str(LEARNING_RATE)+"-SzPtt_"+str(SIZE_PATTERNS)+"-NImg_"+str(NUM_IMAGES)+"-PPImg_"+str(POINTS_PER_IMAGE)