
BATCH_SIZE = 8
TEST_PERCENT = 0.2
PATTERNS_FILE = "patterns.pt"
LEARNING_RATE = 3e-3
EPOCHS = 5
SIZE_PATTERNS = 9 # DISPARI
POINTS_PER_IMAGE = 2
NUM_IMAGES = 500
NUM_CLASSES = 10
RUN_NAME = "MODEL_FIDELITY2"
# RUN_NAME = "LR_"+str(LEARNING_RATE)+"-SzPtt_"+str(SIZE_PATTERNS)+"-NImg_"+str(NUM_IMAGES)+"-PPImg_"+str(POINTS_PER_IMAGE)